FEATURES = [
    "hour",
    "day_of_week",
    "is_weekend",
    "is_rush_hour",
    "current_speed",
    "free_flow_speed",
    "speed_ratio",
    "speed_delta",
    "rolling_speed_3",
    "road_length",
    "max_speed",
    "district_id",
    "avg_speed_1h_ago",
    "avg_speed_yesterday",
    "has_incident",
    "incident_severity",
]